name: ui_playground_example
description: "Demonstrates how to use the ui_playground plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  impaktfull_ui: ^0.76.3
  ui_playground:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
