name: ui_playground_annotations
description: "Annotations package for UI Playground code generation with build_runner."
version: 0.0.3
homepage: https://github.com/impaktfull/flutter_ui_playground

environment:
  sdk: ^3.10.1

dev_dependencies:
  lints: ^6.0.0
